### ISSUE TITLE
Internet Explorer 9 - Content video restart

### ISSUE THREAD

**Issue by sagarsg** [PetroFrolov/vast-video-js#28]
Hi,

I think that Video.js uses a flash player to play video. If I disable the Flash (Shockwave Flash), then video does not play. 

Also, when the flash is enabled, I can see the ad as well as the content video. But, after the mid roll playback, content video restarts instead of continuing playback. I see this behavior only on IE and Safari.

**Comment by PetroFrolov** [comment]
Hi! 

1) It depends of type of video file. Flv can't be played with html5. It try use html5, if it can't then use flash.

2) I know about this bug. It appeared because flash could do seek in file only in stream-mode. Don't use it for midrolls.

P.S. If you want to use flash the best way is use jwplayer/flowplayer/uppod because VideoJS is html5-player with backcompat of Flash.

**Comment by sagarsg** [comment]
Hi,

Thank you for the quick response. I was able to fix the issues.

1) I am using mp4 and webm files. I used techOrder : ["html5","flash"] so that VideoJS uses html5 player first.

2) By default IE9 opens in Document Mode: Quirks and IE10 in Document Mode: IE5 quirks. 
    I am using meta http-equiv="X-UA-Compatible" content="IE=9", to force it to open in Document Mode: IE9 standards. 

This solved the issue for me.

Thanks

**Comment by sagarsg** [comment]
Also, metatag has to be the first line in head.
